aa: rand-m15-n2-p1-mstd0
amp: true
amp_dtype: float16
amp_impl: native
aot_autograd: false
aug_repeats: 0
aug_splits: 0
batch_size: 128
bce_loss: true
bce_target_thresh: null
bn_eps: null
bn_momentum: null
channels_last: false
checkpoint_freq_epoch: 5
checkpoint_hist: 60
class_map: ''
clip_grad: 1.0
clip_mode: norm
color_jitter: null
cooldown_epochs: 5
crop_pct: null
cutmix: 0.0
cutmix_minmax: null
data: null
data_dir: /usr/scratch/abhimanyu/sparsity_exps/imagenet
dataset: torch/Imagenet
dataset_download: true
decay_epochs: 100
decay_milestones:
- 90
- 180
- 270
decay_rate: 0.1
dist_bn: reduce
drop: 0.1
drop_block: null
drop_connect: null
drop_path: 0.1
epoch_repeats: 0.0
epochs: 120
eval_metric: top1
experiment: ''
fast_norm: false
force_cpu: false
fuser: ''
gp: avg
grad_checkpointing: false
hflip: 0.5
img_size: null
in_chans: null
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
layer_decay: null
local_rank: 0
log_interval: 50
log_wandb: false
lr: null
lr_base: 0.0001
lr_base_scale: ''
lr_base_size: 256
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 5.0e-07
mixup: 0.5
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: resnet50
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
no_aug: false
no_ddp_bb: false
no_prefetcher: false
no_resume_opt: false
num_classes: null
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output: resnet50_cifar10
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
sched_on_updates: false
seed: 0
smoothing: 0.0
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchcompile: null
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: null
vflip: 0.0
warmup_epochs: 5
warmup_lr: 0
warmup_prefix: false
weight_decay: 0.05
worker_seeding: all
workers: 8
n_sparsity: 2
m_sparsity: 4 
sparsity_type: DENSE
decay_type: exp
decay_coef: 0.002
dense_steps: 10
fine_tune_steps: 30
structure_decay_flag: true
